Updated Test cases & Workflow File

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -1,14 +1,13 @@
 name: Playwright CI
 
 on:
-  push:
-    branches: [ main ]
-  pull_request:
-    branches: [ main ]
+  workflow_dispatch:
+  repository_dispatch:
+    types: [run-tests]
 
 jobs:
-  run-tests:
-    runs-on: ubuntu-22.04
+  test:
+    runs-on: ubuntu-latest
 
     steps:
       - name: Checkout code
@@ -17,13 +16,29 @@ jobs:
       - name: Setup Node.js
         uses: actions/setup-node@v4
         with:
-          node-version: 18
+          node-version: "20"
 
       - name: Install dependencies
-        run: npm ci
+        run: npm install
+
+      - name: Ensure test-results directory exists
+        run: mkdir -p test-results
 
       - name: Install Playwright Browsers
         run: npx playwright install --with-deps
 
       - name: Run Playwright in virtual display
-        run: xvfb-run -a npx playwright test
+        run: |
+          xvfb-run npx playwright test --project=chromium ./tests/Website.spec.js || true
+      - name: Verify JUnit report
+        if: always()
+        run: |
+          if [ -f test-results/junit-report.xml ]; thengit status
+            echo "JUnit report generated successfully."
+            git status
+          else
+            echo "JUnit report not found. There might be an issue with report generation."
+            exit 1
+          fi
+      - name: Check if JUnit Report exists
+        run: ls -la test-results
